# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 09:44
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('context', models.TextField()),
                ('create_at', models.DateTimeField(default=datetime.datetime(2017, 6, 29, 9, 44, 27, 894090, tzinfo=utc))),
            ],
        ),
    ]
