# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangtestdemo', '0002_articlecategory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['path', 'serialnumber']},
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='serialnumber',
            field=models.IntegerField(default=0),
        ),
    ]
