# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-26 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangtestdemo', '0003_auto_20170526_0819'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articlecategory',
            options={'ordering': ['serialnumber', 'path']},
        ),
    ]
