# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-27 09:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangtestdemo', '0005_auto_20170527_0245'),
    ]

    operations = [
        migrations.AddField(
            model_name='articlecategory',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='articlecategory',
            name='link',
            field=models.URLField(default='', max_length=5000),
        ),
    ]
