# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangtestdemo', '0008_leixing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
            ],
            options={
                'db_table': 'Classification',
                'verbose_name_plural': '\u5206\u7c7b\uff08\u89c6\u9891\u5206\u7c7b\uff09',
            },
        ),
        migrations.CreateModel(
            name='Direction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='\u540d\u79f0')),
                ('classification', models.ManyToManyField(to='djangtestdemo.Classification')),
            ],
            options={
                'db_table': 'Direction',
                'verbose_name_plural': '\u65b9\u5411\uff08\u89c6\u9891\u65b9\u5411\uff09',
            },
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
            ],
            options={
                'verbose_name_plural': '\u96be\u5ea6\u7ea7\u522b',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, '\u4e0b\u7ebf'), (1, '\u4e0a\u7ebf')], default=1, verbose_name='\u72b6\u6001')),
                ('weight', models.IntegerField(default=0, verbose_name='\u6743\u91cd\uff08\u6309\u4ece\u5927\u5230\u5c0f\u6392\u5217\uff09')),
                ('title', models.CharField(max_length=32, verbose_name='\u6807\u9898')),
                ('summary', models.CharField(max_length=32, verbose_name='\u7b80\u4ecb')),
                ('img', models.CharField(max_length=32, verbose_name='\u56fe\u7247')),
                ('href', models.CharField(max_length=256, verbose_name='\u89c6\u9891\u5730\u5740')),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('classification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djangtestdemo.Classification')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djangtestdemo.Level')),
            ],
            options={
                'db_table': 'Video',
                'verbose_name_plural': '\u89c6\u9891',
            },
        ),
    ]
