# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-16 11:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangtestdemo', '0009_classification_direction_level_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='direction',
            name='classification',
        ),
    ]
